mysql:
  datasource:
    test1:
      url: jdbc:mysql://47.106.87.193:3306/test1?useUnicode=true&characterEncoding=utf-8
      username: "case"
      password: "Lh19890624."
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60
    test2:
      url: jdbc:mysql://47.106.87.193:3306/test2?useUnicode=true&characterEncoding=utf-8
      username: "case"
      password: "Lh19890624."
      minPoolSize: 3
      maxPoolSize: 25
      maxLifetime: 20000
      borrowConnectionTimeout: 30
      loginTimeout: 30
      maintenanceInterval: 60
      maxIdleTime: 60

appserver:
  jdbc:
    enable-lazy-proxy: true
    enable-dynamic-switching: true
    default-data-source:
      name: "default"
      base-url: "jdbc:mysql://47.106.87.193:3306"
      db: "liubo"
      search-url: "rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true"
      driver-class-name: "com.mysql.jdbc.Driver"
      username: "case"
      password: "Lh19890624."
      initial-size: 50
      min-idle: 50
      max-idle: 100
      max-active: 400
      max-wait: 2000
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      validation-interval: 30000
      validation-query: "select 1"
      time-between-eviction-runs-millis: 30000
      min-evictable-idle-time-millis: 300000
      remove-abandoned-timeout: 120
      remove-abandoned: true
      default-read-only: false
      default-auto-commit: true
#    data-source:
#      - {name: "slave",db: "aimymusic",base-url: "jdbc:mysql://127.0.0.1:3306",username : "root", password: "123456",search-url: "rewriteBatchedStatements=true&useUnicode=true&characterEncoding=utf8&useSSL=true"}
#      - {name: "minik",db: "", base-url: ""}

  jpa:
    enabled: false
    enable-transaction: true

  mybatis:
    enabled: false
    type-aliases-package: "com.aimymusic.appserver.persist.dto"
    type-handlers-package: "com.aimymusic.appserver.persist.typeHandler"
    mapper-locations: "classpath:mapper/*.xml"

  unify:
    binding-result-aspect: true
    app-version-control-aspect: true
    exception:
      enabled: true
      unify-log: false
      jsonp: ["callback","jsonp"]

  http:
    enabled: false
    time-out-socket: 5000
    time-out-connection: 2000
    time-out-request-connection: 5000
    retry-number: 2
    max-total: 500
    client-properties:
      qq:
        host: "graph.qq.com"
        max-pre-route: 5
        url-map:
          appKey: "1106308466"
          getUserInfo: /user/get_user_info

  shiro:
    app:
      enabled: true

  autowired:
    id-generator: "192.168.10.150"
    encryptor: "4NCMAIfiXsjB9OrG"

  async:
    enabled: false
    executors:
#      - {qualifier: "sql",thread-name-prefix: "Async-sql-",core-pool-size: 10,max-pool-size: 100,queue-capacity: 100}
      - {qualifier: "cache",thread-name-prefix: "Async-cache-",core-pool-size: 10,max-pool-size: 40,queue-capacity: 100}


spring:
  redis:
    session:
      enabled: false
    packages-to-scan: "com.aimymusic.appserver.service"
    expired-time: 3600
    page-size: 20
    host: "106.14.223.238"
    #host: "192.168.10.99"
    port: 6379
    pool:
      max-active: 300
      min-idle: 100
      max-idle: 100
      max-wait: 1000
    password: "111111"
    timeout: 10000
  rabbitmq:
    enabled: false
    #集群条件下的设置
    #addresses: 106.14.176.213:5672,101.132.123.47:5672
    host: 47.106.87.193
    port: 5672
    username: admin
    password: 111111
    listener:
      retry:
        max-interval: 3
        enabled: true
        initial-interval: 3000
      default-requeue-rejected: true

### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl.job.admin.addresses: http://127.0.0.1:8080/xxl-job-admin

### xxl-job executor address
xxl.job.executor.appname: sky-tooks
xxl.job.executor.ip:
xxl.job.executor.port: 9999

### xxl-job, access token
xxl.job.accessToken:

### xxl-job log path
xxl.job.executor.logpath: /Users/bo/logs/xxl-job/jobhandler
### xxl-job log retention days
xxl.job.executor.logretentiondays: -1
