#--------------------------------
# 端口
#--------------------------------
server:
  port: 8082
#  context-path: "/api/"

#--------------------------------
# spring配置
#--------------------------------
spring:
  profiles:
    active: dev

